export const AGENT_ARTIFACT_KIND = Object.freeze({
  RECORD_SUMMARY: 'RECORD_SUMMARY',
  PROJECT_PROGRESS: 'PROJECT_PROGRESS',
})

export const AGENT_RUN_STATUS = Object.freeze({
  QUEUED: 'QUEUED',
  RUNNING: 'RUNNING',
  SUCCEEDED: 'SUCCEEDED',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED',
  LIMIT_EXCEEDED: 'LIMIT_EXCEEDED',
  INVALID_OUTPUT: 'INVALID_OUTPUT',
})

export const ACTIVE_AGENT_RUN_STATUSES = new Set([
  AGENT_RUN_STATUS.QUEUED,
  AGENT_RUN_STATUS.RUNNING,
])
