package com.bionote.agent.tool.bionote;

import com.bionote.agent.report.EvidenceCandidate;
import com.bionote.agent.report.ProjectProgressReadModelService;
import com.bionote.agent.tool.AgentToolContext;
import com.bionote.common.ApiException;
import com.bionote.revision.RevisionDiffService;
import com.bionote.revision.RevisionDtos;
import com.bionote.revision.RevisionQueryService;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;

import java.sql.Timestamp;
import java.time.Instant;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.UUID;

@Service
public class BioNoteAgentReadService {
    private static final Set<String> ACTIVITY_METADATA=Set.of("revisionId","revisionNo","reviewId","restoreOperationId","sourceRevisionId","artifactId","runId","artifactKind","status","triggerType","decision","reason");
    private final JdbcTemplate jdbc;private final ObjectMapper json;private final ProjectProgressReadModelService progress;private final RevisionQueryService revisions;private final RevisionDiffService diffs;
    public BioNoteAgentReadService(JdbcTemplate jdbc,ObjectMapper json,ProjectProgressReadModelService progress,RevisionQueryService revisions,RevisionDiffService diffs){this.jdbc=jdbc;this.json=json;this.progress=progress;this.revisions=revisions;this.diffs=diffs;}
    public ToolPayload projectOverview(AgentToolContext c){Window w=window(c);Map<String,Object> data=progress.overview(c.projectId(),c.actorId(),w.start,w.end);return payload(data,List.of(EvidenceCandidate.project(c.projectId(),String.valueOf(data.get("name")))),null,false,List.of());}
    public ToolPayload listRecords(AgentToolContext c,List<String> statuses,Instant from,Instant to,int page,int size){progress.requireMember(c.projectId(),c.actorId());Window w=window(c);Instant start=max(from,w.start),end=min(to,w.end);int p=Math.max(0,page),s=Math.max(1,Math.min(50,size));List<String> allowed=statuses==null?List.of():statuses.stream().filter(Set.of("IN_PROGRESS","IN_REVIEW","CHANGES_REQUESTED","COMPLETED")::contains).distinct().toList();String statusSql=allowed.isEmpty()?"":" AND r.status IN ("+String.join(",",allowed.stream().map(x->"?").toList())+")";List<Object> args=new ArrayList<>(List.of(c.projectId().toString(),Timestamp.from(start),Timestamp.from(end)));args.addAll(allowed);long total=jdbc.queryForObject("SELECT COUNT(*) FROM experiment_records r WHERE r.project_id=? AND r.deleted_at IS NULL AND r.provisional=FALSE AND r.updated_at>=? AND r.updated_at<=?"+statusSql,Long.class,args.toArray());List<Object> queryArgs=new ArrayList<>(args);queryArgs.add(s);queryArgs.add(p*s);List<Map<String,Object>> rows=jdbc.queryForList("SELECT r.id,r.code,r.title,r.status,r.updated_at,r.current_revision_no,u.display_name creator_name,rv.status review_status,rv.decision_comment review_comment FROM experiment_records r JOIN users u ON u.id=r.creator_id LEFT JOIN reviews rv ON rv.id=r.current_review_id WHERE r.project_id=? AND r.deleted_at IS NULL AND r.provisional=FALSE AND r.updated_at>=? AND r.updated_at<=?"+statusSql+" ORDER BY r.updated_at DESC,r.id DESC LIMIT ? OFFSET ?",queryArgs.toArray());List<EvidenceCandidate> evidence=rows.stream().map(row->EvidenceCandidate.record(c.projectId(),UUID.fromString(row.get("id").toString()),row.get("code")+" "+row.get("title"))).toList();return payload(rows,evidence,Map.of("page",p,"size",s,"totalElements",total),false,List.of());}
    public ToolPayload recordOverview(AgentToolContext c,UUID requested){UUID record=recordFor(c,requested);Map<String,Object> row=recordRow(c,record);Map<String,Object> out=new LinkedHashMap<>();for(String key:List.of("id","code","title","experiment_type","experiment_date","purpose","status","updated_at","current_revision_no"))out.put(camel(key),row.get(key));out.put("creatorName",row.get("creator_name"));out.put("revisionCount",jdbc.queryForObject("SELECT COUNT(*) FROM record_revisions WHERE record_id=? AND revision_no<=?",Long.class,record.toString(),cursorMaxRevision(c)));out.put("attachmentCount",jdbc.queryForObject("SELECT COUNT(*) FROM attachments WHERE record_id=? AND deleted_at IS NULL",Long.class,record.toString()));out.put("currentReview",reviewSummary(row.get("current_review_id")));out.put("finalRevisionId",row.get("final_revision_id"));return payload(out,List.of(EvidenceCandidate.record(c.projectId(),record,row.get("code")+" "+row.get("title"))),null,false,List.of());}
    public ToolPayload listRevisions(AgentToolContext c,UUID requested,Instant from,Instant to){UUID record=recordFor(c,requested);recordRow(c,record);Window w=window(c);Instant start=max(from,w.start),end=min(to,w.end);int max=cursorMaxRevision(c);List<Map<String,Object>> rows=jdbc.queryForList("SELECT rr.id,rr.revision_no,rr.submitted_at,rr.submit_note,rr.content_hash,u.display_name submitter_name,rv.id review_id,rv.status review_status,rv.decision_comment FROM record_revisions rr JOIN users u ON u.id=rr.submitted_by LEFT JOIN reviews rv ON rv.revision_id=rr.id WHERE rr.record_id=? AND rr.revision_no<=? AND rr.submitted_at>=? AND rr.submitted_at<=? ORDER BY rr.revision_no DESC LIMIT 20",record.toString(),max,Timestamp.from(start),Timestamp.from(end));List<EvidenceCandidate> evidence=new ArrayList<>();for(Map<String,Object> row:rows)evidence.add(EvidenceCandidate.revision(c.projectId(),record,UUID.fromString(row.get("id").toString()),"R"+row.get("revision_no")));return payload(rows,evidence,Map.of("size",20),false,List.of());}
    public ToolPayload revisionSummary(AgentToolContext c,UUID revisionId){UUID record=revisionRecord(c,revisionId);RevisionDtos.RevisionDetail detail=revisions.detail(c.actorId(),record,revisionId);Map<String,Object> out=new LinkedHashMap<>();out.put("id",detail.id());out.put("recordId",detail.recordId());out.put("revisionNo",detail.revisionNo());out.put("label",detail.label());out.put("submittedAt",detail.submittedAt());out.put("submitterName",detail.submitterName());out.put("submitNote",limit(detail.submitNote(),1000));out.put("fixedFields",Map.of("title",detail.snapshot().title(),"experimentType",detail.snapshot().experimentType(),"experimentDate",detail.snapshot().experimentDate(),"purpose",limit(detail.snapshot().purpose(),2000)));out.put("templateFields",limitedJson(detail.snapshot().fieldValues(),4000));String text=detail.snapshot().contentPlainText()==null?"":detail.snapshot().contentPlainText();out.put("contentPlainText",limit(text,4000));out.put("truncated",text.length()>4000);out.put("review",detail.review());out.put("attachments",detail.attachments().stream().limit(20).toList());return payload(out,List.of(EvidenceCandidate.revision(c.projectId(),record,revisionId,detail.label())),null,text.length()>4000,List.of());}
    public ToolPayload compare(AgentToolContext c,UUID from,UUID to,boolean hunks){UUID record=revisionRecord(c,from);if(!revisionRecord(c,to).equals(record))throw hidden();RevisionDtos.DiffResult result=diffs.compare(c.actorId(),record,from,to,null,false);List<Map<String,Object>> sections=result.sections().stream().limit(50).map(section->{Map<String,Object> value=new LinkedHashMap<>();value.put("key",section.key());value.put("label",section.label());value.put("kind",section.kind());value.put("status",section.status());value.put("before",limitObject(section.before(),1000));value.put("after",limitObject(section.after(),1000));if(hunks)value.put("textHunks",section.textHunks().stream().limit(20).toList());return value;}).toList();String sourceHash=hash(result.from().contentHash()+":"+result.to().contentHash());Map<String,Object> out=Map.of("recordId",record,"from",result.from(),"to",result.to(),"summary",result.summary(),"sections",sections,"truncated",result.truncated()||result.sections().size()>50,"warnings",result.warnings());return payload(out,List.of(EvidenceCandidate.diff(c.projectId(),record,from,to,sourceHash,"Revision diff")),null,result.truncated()||result.sections().size()>50,result.warnings());}
    public ToolPayload reviews(AgentToolContext c,UUID requested){UUID record=recordFor(c,requested);recordRow(c,record);List<Map<String,Object>> rows=jdbc.queryForList("SELECT rv.id,rv.revision_id,rr.revision_no,u.display_name reviewer_name,rv.status,rv.decision_comment,rv.assigned_at,rv.decided_at FROM reviews rv JOIN record_revisions rr ON rr.id=rv.revision_id JOIN users u ON u.id=rv.reviewer_id WHERE rv.record_id=? AND rr.revision_no<=? ORDER BY rr.revision_no DESC LIMIT 20",record.toString(),cursorMaxRevision(c));List<EvidenceCandidate> evidence=rows.stream().map(row->EvidenceCandidate.review(c.projectId(),record,UUID.fromString(row.get("revision_id").toString()),UUID.fromString(row.get("id").toString()),"R"+row.get("revision_no")+" review")).toList();return payload(rows,evidence,Map.of("size",20),false,List.of());}
    public ToolPayload activity(AgentToolContext c,List<String> types,Instant from,Instant to,int page,int size){progress.requireMember(c.projectId(),c.actorId());Window w=window(c);Instant start=max(from,w.start),end=min(to,w.end);int p=Math.max(0,page),s=Math.max(1,Math.min(50,size));List<String> safe=types==null?List.of():types.stream().filter(x->x!=null&&x.matches("[A-Z0-9_]{1,80}")).distinct().toList();String typeSql=safe.isEmpty()?"":" AND a.event_type IN ("+String.join(",",safe.stream().map(x->"?").toList())+")";List<Object> args=new ArrayList<>(List.of(c.projectId().toString(),Timestamp.from(start),Timestamp.from(end)));args.addAll(safe);long total=jdbc.queryForObject("SELECT COUNT(*) FROM audit_events a WHERE a.project_id=? AND a.created_at>=? AND a.created_at<=?"+typeSql,Long.class,args.toArray());List<Object> q=new ArrayList<>(args);q.add(s);q.add(p*s);List<Map<String,Object>> raw=jdbc.queryForList("SELECT a.id,a.event_type,a.created_at,a.record_id,a.target_type,a.target_id,a.metadata_json,u.display_name actor_name FROM audit_events a LEFT JOIN users u ON u.id=a.actor_id WHERE a.project_id=? AND a.created_at>=? AND a.created_at<=?"+typeSql+" ORDER BY a.created_at DESC,a.id DESC LIMIT ? OFFSET ?",q.toArray());List<Map<String,Object>> rows=new ArrayList<>();List<EvidenceCandidate> evidence=new ArrayList<>();for(Map<String,Object> row:raw){Map<String,Object> value=new LinkedHashMap<>(row);value.remove("metadata_json");value.put("metadata",safeMetadata(String.valueOf(row.get("metadata_json"))));rows.add(value);UUID audit=UUID.fromString(row.get("id").toString());UUID record=row.get("record_id")==null?null:UUID.fromString(row.get("record_id").toString());evidence.add(EvidenceCandidate.audit(c.projectId(),record,audit,String.valueOf(row.get("event_type"))));}return payload(rows,evidence,Map.of("page",p,"size",s,"totalElements",total),false,List.of());}
    public ToolPayload latestReport(AgentToolContext c){progress.requireMember(c.projectId(),c.actorId());List<Map<String,Object>> rows=jdbc.queryForList("SELECT aa.id,aa.created_at,aa.content_json FROM agent_artifacts aa WHERE aa.project_id=? AND aa.artifact_kind='PROJECT_PROGRESS' AND aa.run_id<>? ORDER BY aa.created_at DESC,aa.id DESC LIMIT 1",c.projectId().toString(),c.runId().toString());if(rows.isEmpty())return payload(Map.of("found",false,"derivedArtifact",true),List.of(),null,false,List.of());Map<String,Object> row=rows.get(0);JsonNode content=read(String.valueOf(row.get("content_json")));return payload(Map.of("found",true,"derivedArtifact",true,"artifactId",row.get("id"),"createdAt",row.get("created_at"),"headline",content.path("headline").asText(),"period",content.path("period")),List.of(),null,false,List.of("Previous agent output is derived, not project fact."));}
    private ToolPayload payload(Object data,List<EvidenceCandidate> candidates,Object page,boolean truncated,List<String> warnings){List<JsonNode> views=candidates.stream().map(c->c.publicView(json)).toList();Map<String,Object> out=new LinkedHashMap<>();out.put("data",data);out.put("evidenceCandidates",views);out.put("page",page);out.put("truncated",truncated);out.put("warnings",warnings);return new ToolPayload(out,candidates.stream().map(c->c.encode(json)).toList());}
    private UUID recordFor(AgentToolContext c,UUID requested){if("RECORD".equals(c.subjectType()))return c.recordId();if(requested==null)throw new ApiException(HttpStatus.UNPROCESSABLE_ENTITY,"AGENT_TOOL_ARGUMENTS_INVALID","recordId is required for a project run");return requested;}
    private Map<String,Object> recordRow(AgentToolContext c,UUID record){progress.requireMember(c.projectId(),c.actorId());List<Map<String,Object>> rows=jdbc.queryForList("SELECT r.*,u.display_name creator_name FROM experiment_records r JOIN users u ON u.id=r.creator_id WHERE r.id=? AND r.project_id=? AND r.deleted_at IS NULL AND r.provisional=FALSE",record.toString(),c.projectId().toString());if(rows.isEmpty())throw hidden();return rows.get(0);}
    private UUID revisionRecord(AgentToolContext c,UUID revision){progress.requireMember(c.projectId(),c.actorId());List<String> rows=jdbc.queryForList("SELECT rr.record_id FROM record_revisions rr JOIN experiment_records r ON r.id=rr.record_id WHERE rr.id=? AND r.project_id=? AND r.deleted_at IS NULL AND rr.revision_no<=? AND rr.submitted_at<=?",String.class,revision.toString(),c.projectId().toString(),cursorMaxRevision(c),Timestamp.from(window(c).end));if(rows.isEmpty())throw hidden();UUID record=UUID.fromString(rows.get(0));if("RECORD".equals(c.subjectType())&&!record.equals(c.recordId()))throw hidden();return record;}
    private ApiException hidden(){return new ApiException(HttpStatus.NOT_FOUND,"RESOURCE_NOT_FOUND","Resource not found or inaccessible");}
    private int cursorMaxRevision(AgentToolContext c){JsonNode cursor=cursor(c);return cursor.path("maxRevisionNo").asInt(Integer.MAX_VALUE);}
    private Window window(AgentToolContext c){JsonNode cursor=cursor(c);Instant end=parse(cursor.path("periodEnd").asText(null),Instant.now());Instant start=parse(cursor.path("periodStart").asText(null),end.minusSeconds(7*86400));return new Window(start,end);}
    private JsonNode cursor(AgentToolContext c){String value=jdbc.queryForObject("SELECT input_cursor_json FROM agent_runs WHERE id=?",String.class,c.runId().toString());return read(value);}
    private JsonNode read(String value){try{return json.readTree(value);}catch(Exception e){return json.createObjectNode();}}
    private Map<String,Object> safeMetadata(String value){JsonNode node=read(value);Map<String,Object> out=new LinkedHashMap<>();ACTIVITY_METADATA.forEach(key->{if(node.has(key))out.put(key,json.convertValue(node.get(key),Object.class));});return out;}
    private Object reviewSummary(Object id){if(id==null)return null;List<Map<String,Object>> rows=jdbc.queryForList("SELECT rv.id,rv.revision_id,rv.status,rv.decision_comment,rv.decided_at,u.display_name reviewer_name FROM reviews rv JOIN users u ON u.id=rv.reviewer_id WHERE rv.id=?",id.toString());return rows.isEmpty()?null:rows.get(0);}
    private String limitedJson(Object value,int max){try{return limit(json.writeValueAsString(value),max);}catch(Exception e){return "{}";}}
    private Object limitObject(Object value,int max){String text=value==null?null:String.valueOf(value);return limit(text,max);}
    private String limit(String value,int max){if(value==null)return null;return value.length()<=max?value:value.substring(0,max);}
    private String camel(String value){StringBuilder out=new StringBuilder();boolean upper=false;for(char ch:value.toCharArray()){if(ch=='_'){upper=true;continue;}out.append(upper?Character.toUpperCase(ch):ch);upper=false;}return out.toString();}
    private Instant parse(String value,Instant fallback){try{return value==null?fallback:Instant.parse(value);}catch(Exception e){return fallback;}}
    private Instant max(Instant value,Instant floor){return value==null||value.isBefore(floor)?floor:value;}
    private Instant min(Instant value,Instant ceiling){return value==null||value.isAfter(ceiling)?ceiling:value;}
    private String hash(String value){try{return java.util.HexFormat.of().formatHex(java.security.MessageDigest.getInstance("SHA-256").digest(value.getBytes(java.nio.charset.StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
    public record ToolPayload(Map<String,Object> data,List<String> candidates){}
    private record Window(Instant start,Instant end){}
}
