package com.bionote.agent.tool.bionote;

import com.bionote.agent.report.EvidenceCandidate;
import com.bionote.agent.report.ProjectProgressReadModelService;
import com.bionote.agent.tool.AgentToolContext;
import com.bionote.common.ApiException;
import com.bionote.revision.RevisionDiffService;
import com.bionote.revision.RevisionDtos;
import com.bionote.revision.RevisionQueryService;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;

import java.time.Instant;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.UUID;

@Service
public class BioNoteAgentReadService {
    private static final Set<String> ACTIVITY_METADATA=Set.of("revisionId","revisionNo","reviewId","restoreOperationId","sourceRevisionId","artifactId","runId","artifactKind","status","triggerType","decision","reason");
    private final BioNoteAgentQueryStore store;private final ObjectMapper json;private final ProjectProgressReadModelService progress;private final RevisionQueryService revisions;private final RevisionDiffService diffs;
    public BioNoteAgentReadService(BioNoteAgentQueryStore store,ObjectMapper json,ProjectProgressReadModelService progress,RevisionQueryService revisions,RevisionDiffService diffs){this.store=store;this.json=json;this.progress=progress;this.revisions=revisions;this.diffs=diffs;}
    public ToolPayload projectOverview(AgentToolContext c){Window w=window(c);Map<String,Object> data=progress.overview(c.projectId(),c.actorId(),w.start,w.end);return payload(data,List.of(EvidenceCandidate.project(c.projectId(),String.valueOf(data.get("name")))),null,false,List.of());}
    public ToolPayload listRecords(AgentToolContext c,List<String> statuses,Instant from,Instant to,int page,int size){progress.requireMember(c.projectId(),c.actorId());Window w=window(c);Instant start=max(from,w.start),end=min(to,w.end);int p=Math.max(0,page),s=Math.max(1,Math.min(50,size));List<String> allowed=statuses==null?List.of():statuses.stream().filter(Set.of("IN_PROGRESS","IN_REVIEW","CHANGES_REQUESTED","COMPLETED")::contains).distinct().toList();BioNoteAgentQueryStore.PageSlice slice=store.listRecords(c.projectId(),start,end,allowed,p,s);List<Map<String,Object>> rows=slice.items();List<EvidenceCandidate> evidence=rows.stream().map(row->EvidenceCandidate.record(c.projectId(),UUID.fromString(row.get("id").toString()),row.get("code")+" "+row.get("title"))).toList();return payload(rows,evidence,Map.of("page",p,"size",s,"totalElements",slice.total()),false,List.of());}
    public ToolPayload recordOverview(AgentToolContext c,UUID requested){UUID record=recordFor(c,requested);Map<String,Object> row=recordRow(c,record);Map<String,Object> out=new LinkedHashMap<>();for(String key:List.of("id","code","title","experiment_type","experiment_date","purpose","status","updated_at","current_revision_no"))out.put(camel(key),row.get(key));out.put("creatorName",row.get("creator_name"));out.put("revisionCount",store.revisionCount(record,cursorMaxRevision(c)));out.put("attachmentCount",store.activeAttachmentCount(record));out.put("currentReview",reviewSummary(row.get("current_review_id")));out.put("finalRevisionId",row.get("final_revision_id"));return payload(out,List.of(EvidenceCandidate.record(c.projectId(),record,row.get("code")+" "+row.get("title"))),null,false,List.of());}
    public ToolPayload listRevisions(AgentToolContext c,UUID requested,Instant from,Instant to){UUID record=recordFor(c,requested);recordRow(c,record);Window w=window(c);Instant start=max(from,w.start),end=min(to,w.end);int max=cursorMaxRevision(c);List<Map<String,Object>> rows=store.listRevisions(record,max,start,end);List<EvidenceCandidate> evidence=new ArrayList<>();for(Map<String,Object> row:rows)evidence.add(EvidenceCandidate.revision(c.projectId(),record,UUID.fromString(row.get("id").toString()),"R"+row.get("revision_no")));return payload(rows,evidence,Map.of("size",20),false,List.of());}
    public ToolPayload revisionSummary(AgentToolContext c,UUID revisionId){UUID record=revisionRecord(c,revisionId);RevisionDtos.RevisionDetail detail=revisions.detail(c.actorId(),record,revisionId);Map<String,Object> out=new LinkedHashMap<>();out.put("id",detail.id());out.put("recordId",detail.recordId());out.put("revisionNo",detail.revisionNo());out.put("label",detail.label());out.put("submittedAt",detail.submittedAt());out.put("submitterName",detail.submitterName());out.put("submitNote",limit(detail.submitNote(),1000));out.put("fixedFields",Map.of("title",detail.snapshot().title(),"experimentType",detail.snapshot().experimentType(),"experimentDate",detail.snapshot().experimentDate(),"purpose",limit(detail.snapshot().purpose(),2000)));out.put("templateFields",limitedJson(detail.snapshot().fieldValues(),4000));String text=detail.snapshot().contentPlainText()==null?"":detail.snapshot().contentPlainText();out.put("contentPlainText",limit(text,4000));out.put("truncated",text.length()>4000);out.put("review",detail.review());out.put("attachments",detail.attachments().stream().limit(20).toList());return payload(out,List.of(EvidenceCandidate.revision(c.projectId(),record,revisionId,detail.label())),null,text.length()>4000,List.of());}
    public ToolPayload compare(AgentToolContext c,UUID from,UUID to,boolean hunks){UUID record=revisionRecord(c,from);if(!revisionRecord(c,to).equals(record))throw hidden();RevisionDtos.DiffResult result=diffs.compare(c.actorId(),record,from,to,null,false);List<Map<String,Object>> sections=result.sections().stream().limit(50).map(section->{Map<String,Object> value=new LinkedHashMap<>();value.put("key",section.key());value.put("label",section.label());value.put("kind",section.kind());value.put("status",section.status());value.put("before",limitObject(section.before(),1000));value.put("after",limitObject(section.after(),1000));if(hunks)value.put("textHunks",section.textHunks().stream().limit(20).toList());return value;}).toList();String sourceHash=hash(result.from().contentHash()+":"+result.to().contentHash());Map<String,Object> out=Map.of("recordId",record,"from",result.from(),"to",result.to(),"summary",result.summary(),"sections",sections,"truncated",result.truncated()||result.sections().size()>50,"warnings",result.warnings());return payload(out,List.of(EvidenceCandidate.diff(c.projectId(),record,from,to,sourceHash,"Revision diff")),null,result.truncated()||result.sections().size()>50,result.warnings());}
    public ToolPayload reviews(AgentToolContext c,UUID requested){UUID record=recordFor(c,requested);recordRow(c,record);List<Map<String,Object>> rows=store.listReviews(record,cursorMaxRevision(c));List<EvidenceCandidate> evidence=rows.stream().map(row->EvidenceCandidate.review(c.projectId(),record,UUID.fromString(row.get("revision_id").toString()),UUID.fromString(row.get("id").toString()),"R"+row.get("revision_no")+" review")).toList();return payload(rows,evidence,Map.of("size",20),false,List.of());}
    public ToolPayload activity(AgentToolContext c,List<String> types,Instant from,Instant to,int page,int size){progress.requireMember(c.projectId(),c.actorId());Window w=window(c);Instant start=max(from,w.start),end=min(to,w.end);int p=Math.max(0,page),s=Math.max(1,Math.min(50,size));List<String> safe=types==null?List.of():types.stream().filter(x->x!=null&&x.matches("[A-Z0-9_]{1,80}")).distinct().toList();BioNoteAgentQueryStore.PageSlice slice=store.activity(c.projectId(),start,end,safe,p,s);List<Map<String,Object>> rows=new ArrayList<>();List<EvidenceCandidate> evidence=new ArrayList<>();for(Map<String,Object> row:slice.items()){Map<String,Object> value=new LinkedHashMap<>(row);value.remove("metadata_json");value.put("metadata",safeMetadata(String.valueOf(row.get("metadata_json"))));rows.add(value);UUID audit=UUID.fromString(row.get("id").toString());UUID record=row.get("record_id")==null?null:UUID.fromString(row.get("record_id").toString());evidence.add(EvidenceCandidate.audit(c.projectId(),record,audit,String.valueOf(row.get("event_type"))));}return payload(rows,evidence,Map.of("page",p,"size",s,"totalElements",slice.total()),false,List.of());}
    public ToolPayload latestReport(AgentToolContext c){progress.requireMember(c.projectId(),c.actorId());var found=store.latestProjectReport(c.projectId(),c.runId());if(found.isEmpty())return payload(Map.of("found",false,"derivedArtifact",true),List.of(),null,false,List.of());Map<String,Object> row=found.get();JsonNode content=read(String.valueOf(row.get("content_json")));return payload(Map.of("found",true,"derivedArtifact",true,"artifactId",row.get("id"),"createdAt",row.get("created_at"),"headline",content.path("headline").asText(),"period",content.path("period")),List.of(),null,false,List.of("Previous agent output is derived, not project fact."));}
    private ToolPayload payload(Object data,List<EvidenceCandidate> candidates,Object page,boolean truncated,List<String> warnings){List<JsonNode> views=candidates.stream().map(c->c.publicView(json)).toList();Map<String,Object> out=new LinkedHashMap<>();out.put("data",data);out.put("evidenceCandidates",views);out.put("page",page);out.put("truncated",truncated);out.put("warnings",warnings);return new ToolPayload(out,candidates.stream().map(c->c.encode(json)).toList());}
    private UUID recordFor(AgentToolContext c,UUID requested){if("RECORD".equals(c.subjectType()))return c.recordId();if(requested==null)throw new ApiException(HttpStatus.UNPROCESSABLE_ENTITY,"AGENT_TOOL_ARGUMENTS_INVALID","recordId is required for a project run");return requested;}
    private Map<String,Object> recordRow(AgentToolContext c,UUID record){progress.requireMember(c.projectId(),c.actorId());return store.findRecord(record,c.projectId()).orElseThrow(this::hidden);}
    private UUID revisionRecord(AgentToolContext c,UUID revision){progress.requireMember(c.projectId(),c.actorId());UUID record=store.findRevisionRecord(revision,c.projectId(),cursorMaxRevision(c),window(c).end).orElseThrow(this::hidden);if("RECORD".equals(c.subjectType())&&!record.equals(c.recordId()))throw hidden();return record;}
    private ApiException hidden(){return new ApiException(HttpStatus.NOT_FOUND,"RESOURCE_NOT_FOUND","Resource not found or inaccessible");}
    private int cursorMaxRevision(AgentToolContext c){JsonNode cursor=cursor(c);return cursor.path("maxRevisionNo").asInt(Integer.MAX_VALUE);}
    private Window window(AgentToolContext c){JsonNode cursor=cursor(c);Instant end=parse(cursor.path("periodEnd").asText(null),Instant.now());Instant start=parse(cursor.path("periodStart").asText(null),end.minusSeconds(7*86400));return new Window(start,end);}
    private JsonNode cursor(AgentToolContext c){return read(store.inputCursorJson(c.runId()));}
    private JsonNode read(String value){try{return json.readTree(value);}catch(Exception e){return json.createObjectNode();}}
    private Map<String,Object> safeMetadata(String value){JsonNode node=read(value);Map<String,Object> out=new LinkedHashMap<>();ACTIVITY_METADATA.forEach(key->{if(node.has(key))out.put(key,json.convertValue(node.get(key),Object.class));});return out;}
    private Object reviewSummary(Object id){if(id==null)return null;return store.findReview(UUID.fromString(id.toString())).orElse(null);}
    private String limitedJson(Object value,int max){try{return limit(json.writeValueAsString(value),max);}catch(Exception e){return "{}";}}
    private Object limitObject(Object value,int max){String text=value==null?null:String.valueOf(value);return limit(text,max);}
    private String limit(String value,int max){if(value==null)return null;return value.length()<=max?value:value.substring(0,max);}
    private String camel(String value){StringBuilder out=new StringBuilder();boolean upper=false;for(char ch:value.toCharArray()){if(ch=='_'){upper=true;continue;}out.append(upper?Character.toUpperCase(ch):ch);upper=false;}return out.toString();}
    private Instant parse(String value,Instant fallback){try{return value==null?fallback:Instant.parse(value);}catch(Exception e){return fallback;}}
    private Instant max(Instant value,Instant floor){return value==null||value.isBefore(floor)?floor:value;}
    private Instant min(Instant value,Instant ceiling){return value==null||value.isAfter(ceiling)?ceiling:value;}
    private String hash(String value){try{return java.util.HexFormat.of().formatHex(java.security.MessageDigest.getInstance("SHA-256").digest(value.getBytes(java.nio.charset.StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
    public record ToolPayload(Map<String,Object> data,List<String> candidates){}
    private record Window(Instant start,Instant end){}
}
