package com.bionote.agent.api;

import com.bionote.agent.config.AgentProperties;
import com.bionote.agent.prompt.PromptVersion;
import com.bionote.agent.prompt.PromptVersionService;
import com.bionote.agent.runtime.AgentRunRecord;
import com.bionote.agent.runtime.AgentRunRepository;
import com.bionote.agent.trace.AgentStepRepository;
import com.bionote.collaboration.event.AgentArtifactViewedEvent;
import com.bionote.collaboration.event.AgentRunRequestedEvent;
import com.bionote.collaboration.event.DomainEventPublisher;
import com.bionote.common.ApiException;
import com.bionote.common.PagedResponse;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.sql.Timestamp;
import java.time.Duration;
import java.time.Instant;
import java.util.ArrayList;
import java.util.HexFormat;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;

@Service
public class AgentRunService {
    private final AgentProperties properties;private final AgentRunRepository runs;private final PromptVersionService prompts;private final AgentStepRepository steps;private final JdbcTemplate jdbc;private final ObjectMapper json;private final DomainEventPublisher events;
    public AgentRunService(AgentProperties properties,AgentRunRepository runs,PromptVersionService prompts,AgentStepRepository steps,JdbcTemplate jdbc,ObjectMapper json,DomainEventPublisher events){this.properties=properties;this.runs=runs;this.prompts=prompts;this.steps=steps;this.jdbc=jdbc;this.json=json;this.events=events;}
    @Transactional public AgentDtos.RunView createRecord(UUID actor,UUID recordId,AgentDtos.CreateRunRequest request,String key){requireEnabled();Map<String,Object> record=record(recordId,actor);if(!actor.toString().equals(record.get("creator_id").toString()))throw new ApiException(HttpStatus.FORBIDDEN,"ACCESS_DENIED","Only the record creator can generate a summary");if(!"RECORD_SUMMARY".equals(request.artifactKind()))throw invalid("artifactKind must be RECORD_SUMMARY");UUID project=UUID.fromString(record.get("project_id").toString());Instant end=Instant.now(),start=((Timestamp)record.get("created_at")).toInstant();return create(actor,"RECORD_SUMMARY","RECORD",recordId,project,recordId,start,end,request.focus(),key,null,"MANUAL");}
    @Transactional public AgentDtos.RunView createProject(UUID actor,UUID projectId,AgentDtos.CreateRunRequest request,String key){requireEnabled();String role=member(projectId,actor);if(!"OWNER".equals(role))throw new ApiException(HttpStatus.FORBIDDEN,"ACCESS_DENIED","Only project owners can generate project progress reports");if(!"PROJECT_PROGRESS".equals(request.artifactKind()))throw invalid("artifactKind must be PROJECT_PROGRESS");Instant end=request.periodEnd()==null?Instant.now():request.periodEnd(),start=request.periodStart()==null?end.minus(Duration.ofDays(7)):request.periodStart();if(start.isAfter(end)||Duration.between(start,end).compareTo(Duration.ofDays(90))>0)throw invalid("Report period must be ordered and no longer than 90 days");return create(actor,"PROJECT_PROGRESS","PROJECT",projectId,projectId,null,start,end,request.focus(),key,null,"MANUAL");}
    public AgentDtos.RunView get(UUID actor,UUID runId){AgentRunRecord run=authorizedRun(actor,runId,false);return view(run);}
    public PagedResponse<AgentDtos.StepView> steps(UUID actor,UUID runId,int page,int size){AgentRunRecord run=authorizedRun(actor,runId,true);int p=Math.max(0,page),s=Math.max(1,Math.min(100,size));List<AgentStepRepository.Step> all=steps.list(run.id());List<AgentDtos.StepView> data=all.stream().skip((long)p*s).limit(s).map(value->new AgentDtos.StepView(value.id(),value.stepNo(),value.stepType(),value.toolName(),value.request(),value.response(),value.contentHash(),value.latencyMs(),value.inputTokens(),value.outputTokens(),value.createdAt())).toList();return PagedResponse.of(data,p,s,all.size());}
    @Transactional public AgentDtos.RunView cancel(UUID actor,UUID runId){AgentRunRecord run=authorizedRun(actor,runId,false);String role=member(run.projectId(),actor);if(!run.requestedBy().equals(actor)&&!"OWNER".equals(role))throw new ApiException(HttpStatus.FORBIDDEN,"ACCESS_DENIED","Only the requester or project owner can cancel this run");if(terminal(run.status()))throw new ApiException(HttpStatus.CONFLICT,"AGENT_RUN_NOT_CANCELLABLE","Agent run is already terminal");runs.requestCancel(runId);return view(runs.load(runId));}
    @Transactional public AgentDtos.RunView rerun(UUID actor,UUID runId,String key){AgentRunRecord old=authorizedRun(actor,runId,false);JsonNode request=read(old.requestJson());AgentDtos.CreateRunRequest value=new AgentDtos.CreateRunRequest(old.artifactKind(),instant(request.path("periodStart").asText(null)),instant(request.path("periodEnd").asText(null)),request.path("focus").asText(null));if("RECORD".equals(old.subjectType())){Map<String,Object> record=record(old.recordId(),actor);if(!actor.toString().equals(record.get("creator_id").toString()))throw new ApiException(HttpStatus.FORBIDDEN,"ACCESS_DENIED","Only the record creator can rerun this summary");return create(actor,old.artifactKind(),old.subjectType(),old.subjectId(),old.projectId(),old.recordId(),value.periodStart(),value.periodEnd(),value.focus(),key,old.id(),"RERUN");}if(!"OWNER".equals(member(old.projectId(),actor)))throw new ApiException(HttpStatus.FORBIDDEN,"ACCESS_DENIED","Only project owners can rerun progress reports");return create(actor,old.artifactKind(),old.subjectType(),old.subjectId(),old.projectId(),null,value.periodStart(),value.periodEnd(),value.focus(),key,old.id(),"RERUN");}
    public PagedResponse<AgentDtos.ArtifactSummary> recordArtifacts(UUID actor,UUID recordId,int page,int size){Map<String,Object> record=record(recordId,actor);return artifacts(actor,UUID.fromString(record.get("project_id").toString()),recordId,page,size);}
    public PagedResponse<AgentDtos.ArtifactSummary> projectArtifacts(UUID actor,UUID projectId,int page,int size){member(projectId,actor);return artifacts(actor,projectId,null,page,size);}
    public AgentDtos.ArtifactView artifact(UUID actor,UUID id){List<Map<String,Object>> rows=jdbc.queryForList("SELECT * FROM agent_artifacts WHERE id=?",id.toString());if(rows.isEmpty())throw hidden();Map<String,Object> row=rows.get(0);UUID project=UUID.fromString(row.get("project_id").toString());member(project,actor);UUID record=uuid(row.get("record_id"));events.publish(new AgentArtifactViewedEvent(UUID.randomUUID(),actor,project,record,Instant.now(),UUID.fromString(row.get("run_id").toString()),row.get("artifact_kind").toString(),id));return artifactView(row);}
    private AgentDtos.RunView create(UUID actor,String kind,String subjectType,UUID subjectId,UUID project,UUID record,Instant start,Instant end,String focus,String key,UUID parent,String trigger){String idem=key(key);String trimmed=focus==null?"":focus.trim();if(trimmed.length()>500)throw invalid("focus exceeds 500 characters");Map<String,Object> request=new LinkedHashMap<>();request.put("artifactKind",kind);request.put("periodStart",start);request.put("periodEnd",end);request.put("focus",trimmed);String requestJson=write(request),payload=sha("RECORD_SUMMARY".equals(kind)?kind+"|"+subjectId+"|"+trimmed:kind+"|"+subjectId+"|"+start+"|"+end+"|"+trimmed);AgentRunRecord existing=runs.findByRequesterKey(actor,idem);if(existing!=null){if(existing.payloadHash().equals(payload))return view(existing);throw new ApiException(HttpStatus.CONFLICT,"IDEMPOTENCY_CONFLICT","Idempotency key was used for a different agent request");}rate(actor,project,subjectId,kind,payload);PromptVersion prompt=prompts.active(promptName(kind));UUID id=UUID.randomUUID();Map<String,Object> cursor=new LinkedHashMap<>();cursor.put("periodStart",start);cursor.put("periodEnd",end);cursor.put("createdAt",Instant.now());cursor.put("projectVersion",jdbc.queryForObject("SELECT version FROM projects WHERE id=?",Long.class,project.toString()));cursor.put("maxRevisionNo",record==null?Integer.MAX_VALUE:jdbc.queryForObject("SELECT current_revision_no FROM experiment_records WHERE id=?",Integer.class,record.toString()));if(record!=null)cursor.put("recordVersion",jdbc.queryForObject("SELECT version FROM experiment_records WHERE id=?",Long.class,record.toString()));String limits=write(Map.of("maxSteps",properties.getMaxSteps(),"maxToolCalls",properties.getMaxToolCalls(),"maxModelCalls",properties.getMaxModelCalls(),"maxDurationMs",properties.getMaxDurationMs(),"maxOutputTokens",properties.getMaxOutputTokens(),"maxRepairTurns",properties.getMaxRepairTurns()));AgentRunRecord run=runs.enqueue(id,kind,subjectType,subjectId,project,record,actor,trigger,properties.getProvider(),properties.getModel(),prompt.id(),parent,idem,requestJson,payload,write(cursor),limits);events.publish(new AgentRunRequestedEvent(UUID.randomUUID(),actor,project,record,Instant.now(),id,kind,trigger,"QUEUED"));return view(run);}
    private void rate(UUID actor,UUID project,UUID subject,String kind,String payload){Integer user=jdbc.queryForObject("SELECT COUNT(*) FROM agent_runs WHERE requested_by=? AND status IN ('QUEUED','RUNNING')",Integer.class,actor.toString());Integer projectActive=jdbc.queryForObject("SELECT COUNT(*) FROM agent_runs WHERE project_id=? AND status IN ('QUEUED','RUNNING')",Integer.class,project.toString());if(user>=properties.getMaxConcurrentPerUser()||projectActive>=properties.getMaxConcurrentPerProject())throw limited();Instant cutoff=Instant.now().minusSeconds(Math.max(0,properties.getSameSubjectCooldownSeconds()));Integer recent=jdbc.queryForObject("SELECT COUNT(*) FROM agent_runs WHERE subject_id=? AND artifact_kind=? AND payload_hash=? AND created_at>=?",Integer.class,subject.toString(),kind,payload,Timestamp.from(cutoff));if(recent>0)throw limited();}
    private AgentRunRecord authorizedRun(UUID actor,UUID id,boolean trace){AgentRunRecord run;try{run=runs.load(id);}catch(Exception e){throw hidden();}String role=member(run.projectId(),actor);if(trace&&!run.requestedBy().equals(actor)&&!"OWNER".equals(role))throw hidden();return run;}
    private Map<String,Object> record(UUID id,UUID actor){List<Map<String,Object>> rows=jdbc.queryForList("SELECT r.* FROM experiment_records r JOIN project_members pm ON pm.project_id=r.project_id AND pm.user_id=? WHERE r.id=? AND r.deleted_at IS NULL AND r.provisional=FALSE",actor.toString(),id.toString());if(rows.isEmpty())throw hidden();return rows.get(0);}
    private String member(UUID project,UUID actor){List<String> roles=jdbc.queryForList("SELECT role FROM project_members WHERE project_id=? AND user_id=?",String.class,project.toString(),actor.toString());if(roles.isEmpty())throw hidden();return roles.get(0);}
    private PagedResponse<AgentDtos.ArtifactSummary> artifacts(UUID actor,UUID project,UUID record,int page,int size){member(project,actor);int p=Math.max(0,page),s=Math.max(1,Math.min(100,size));String where=record==null?"project_id=?":"record_id=?";String id=record==null?project.toString():record.toString();long total=jdbc.queryForObject("SELECT COUNT(*) FROM agent_artifacts WHERE "+where,Long.class,id);List<Map<String,Object>> rows=jdbc.queryForList("SELECT * FROM agent_artifacts WHERE "+where+" ORDER BY created_at DESC,id DESC LIMIT ? OFFSET ?",id,s,p*s);return PagedResponse.of(rows.stream().map(this::artifactSummary).toList(),p,s,total);}
    private AgentDtos.RunView view(AgentRunRecord run){List<String> artifacts=jdbc.queryForList("SELECT id FROM agent_artifacts WHERE run_id=?",String.class,run.id().toString());return new AgentDtos.RunView(run.id(),run.status(),run.artifactKind(),run.subjectType(),run.subjectId(),run.projectId(),run.recordId(),run.requestedBy(),run.triggerType(),run.provider(),run.model(),run.promptVersionId(),run.parentRunId(),run.stepCount(),run.toolCallCount(),run.inputTokens(),run.outputTokens(),run.errorCode(),run.errorMessage(),run.createdAt(),run.startedAt(),run.finishedAt(),artifacts.isEmpty()?null:UUID.fromString(artifacts.get(0)));}
    private AgentDtos.ArtifactSummary artifactSummary(Map<String,Object> row){JsonNode content=read(row.get("content_json").toString());return new AgentDtos.ArtifactSummary(UUID.fromString(row.get("id").toString()),UUID.fromString(row.get("run_id").toString()),row.get("artifact_kind").toString(),UUID.fromString(row.get("project_id").toString()),uuid(row.get("record_id")),content.path("headline").asText(),content.path("period"),row.get("content_hash").toString(),((Timestamp)row.get("created_at")).toInstant());}
    private AgentDtos.ArtifactView artifactView(Map<String,Object> row){return new AgentDtos.ArtifactView(UUID.fromString(row.get("id").toString()),UUID.fromString(row.get("run_id").toString()),row.get("artifact_kind").toString(),UUID.fromString(row.get("project_id").toString()),uuid(row.get("record_id")),read(row.get("content_json").toString()),read(row.get("evidence_json").toString()),row.get("content_hash").toString(),((Timestamp)row.get("created_at")).toInstant());}
    private void requireEnabled(){if(!properties.isEnabled())throw new ApiException(HttpStatus.SERVICE_UNAVAILABLE,"AGENT_DISABLED","Agent functionality is disabled");}
    private String promptName(String kind){return "RECORD_SUMMARY".equals(kind)?"record-summary":"project-progress";}
    private String key(String value){if(value==null||value.isBlank()||value.trim().length()>160)throw invalid("A valid Idempotency-Key is required");return value.trim();}
    private boolean terminal(String status){return List.of("SUCCEEDED","FAILED","CANCELLED","LIMIT_EXCEEDED","INVALID_OUTPUT").contains(status);}
    private ApiException invalid(String message){return new ApiException(HttpStatus.BAD_REQUEST,"AGENT_INVALID_REQUEST",message);}
    private ApiException hidden(){return new ApiException(HttpStatus.NOT_FOUND,"RESOURCE_NOT_FOUND","Resource not found or inaccessible");}
    private ApiException limited(){return new ApiException(HttpStatus.TOO_MANY_REQUESTS,"AGENT_RATE_LIMITED","Agent run rate limit exceeded");}
    private String write(Object value){try{return json.writeValueAsString(value);}catch(Exception e){throw new IllegalArgumentException(e);}}
    private JsonNode read(String value){try{return json.readTree(value);}catch(Exception e){return json.createObjectNode();}}
    private String sha(String value){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(value.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
    private UUID uuid(Object value){return value==null?null:UUID.fromString(value.toString());}
    private Instant instant(String value){try{return value==null?null:Instant.parse(value);}catch(Exception e){return null;}}
}
